### ISSUE TITLE
Fix responsive styling of forging section

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-ui#105]
Expected behaviour:
The fields should align responsive.

Current behaviour:
Breaks when decreasing window size.

How top replicate:
Decrease window size of the forging section.

**Comment by karmacoma** [comment]
Reopening this issue to resolve some more responsive bugs within the forging section.

**Overflowing page navigation bar:**

![page-nav-broken](https://cloud.githubusercontent.com/assets/8068/24427363/fb37e184-140a-11e7-8153-777d0c4f1fec.png)

**Overflowing forging navigation bar:**

![forging-nav-broken](https://cloud.githubusercontent.com/assets/8068/24427416/25cf3366-140b-11e7-8702-1c13883b8826.png)

**Broken registration button and overflowing panel:**

![registration-and-panel-broken](https://cloud.githubusercontent.com/assets/8068/24427444/38cc7848-140b-11e7-8ca3-95f7915978fd.png)
