### ISSUE TITLE
More effective forging controller

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-ui#108]
Current behaviour:
The forging controller makes 4 API calls, with today, 1 day, 7 days and 30 days. 
https://github.com/LiskHQ/lisk-ui/blob/development/js/controllers/forgingController.js#L182

Expected behaviour:
The forging controller makes 1 API call (30 days) and from there can substract from the given array the days (by timestamp).

Is that possible?

**Comment by Isabello** [comment]
The amount forged may vary from the 30 day amount due to fees and missed
blocks. So while it would provide a brief overview, it won't be as accurate
as users might want.

**Comment by Tosch110** [comment]
Thanks for the insights Isabella.
