### ISSUE TITLE
Dapp Installation states "Passphrase" and "Password"

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-ui#28]
We need to unify it.

E.g.

>Please enter node master password.

>Master Password

>The master password is only accessible by the node owner. It's an auto generated and can be found at the end of the config.json file.

**Comment by fix** [comment]
@max you should reopen this one.
cross reference with https://github.com/LiskHQ/lisk-ui/issues/14

**Comment by max** [comment]
Just FYI you guys keep mentioning `@max`. That does not do what you think it does.

**Comment by fix** [comment]
how sorry my bad! This is his chat nick. I'll try to do better next time.


BTW, can you imagine, my nick is @fix !!!
