### ISSUE TITLE
After enabling 2nd Passphrase it's impossible to vote

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-ui#30]
From: https://github.com/LiskHQ/lisk/issues/70

> After enabling a 2nd passphrase in version 0.2.0 its impossible to vote or unvote.

**Comment by arisAlexis** [comment]
please resolve it before mainnet launch milestone , people can't vote and they can't be in the top 101 or we need to inform everybody that we changed delegate etc. It is important

**Comment by karmacoma** [comment]
@arisAlexis It will be fixed very soon indeed, I tagged it with milestone because it needs to be done asap not later. Sorry for any confusion.
