### ISSUE TITLE
MS Edge browser error during sign in.  BIP39 error.

### ISSUE THREAD

**Issue by qtipwax** [LiskHQ/lisk-ui#31]
Trying to sign in using copy and paste of the passphrase version 0.2.0 testnet.  No problem with my chrome or firefox browser.  Might need an "If MS Edge....." statement?
<img width="434" alt="msedge" src="https://cloud.githubusercontent.com/assets/12992198/14940145/22a90494-0f1d-11e6-9045-abfa74a6cf54.PNG">
<img width="180" alt="edgever" src="https://cloud.githubusercontent.com/assets/12992198/14940146/2c47607c-0f1d-11e6-80dc-26e6df3b3a6d.PNG">

**Comment by mrv777** [comment]
Looks like this was addressed in their github:
https://github.com/bitpay/bitcore-mnemonic/pull/33

I would update the code to match 1.1.1's code

**Comment by qtipwax** [comment]
Tested works  Good job!
