### ISSUE TITLE
After logging out.  Logging in as a new user shows the logged out account name.

### ISSUE THREAD

**Issue by qtipwax** [LiskHQ/lisk-ui#32]
Testnet 0.2.0 Firefox and Chrome I used to reproduce.  After logging out Alice, I logged in using Bob's passphrase.  Unfortunately, doing this show Alice's and not Bob's name, even though it's Bob's account.  In the example I pasted Bob's passphrase back into notepad proving that was the contents of the clipboard.
[Recording_20160501_1640.pdf](https://github.com/LiskHQ/lisk-ui/files/244407/Recording_20160501_1640.pdf)

**Comment by karmacoma** [comment]
This issue should have been resolved here: #29. Thanks for reporting 👍
