### ISSUE TITLE
Error creating Multisig Step 2/3

### ISSUE THREAD

**Issue by qtipwax** [LiskHQ/lisk-ui#35]
Using Testnet 0.2.1.  Chrome browser.  Error when pressing "NEXT".  When hitting Enter on the keyboard it takes the input.

<img width="439" alt="error" src="https://cloud.githubusercontent.com/assets/12992198/15053213/5bf12712-12b6-11e6-95a6-66aec1b1d922.PNG">

**Comment by karmacoma** [comment]
> Pressing enter confirms each member

**Next** moves to the next page in the wizard.

Do you think this is not clear enough?

**Comment by qtipwax** [comment]
Thinking something like "**Please press Enter to add each member before pressing NEXT**" 
Bold or standout text.  This might help clarify.

**Comment by mrv777** [comment]
Also, below the title **Step 2/3 - Specify Group Members**
It does say  

> Add group members by typing in their LISK address and pressing enter

Only thing I can think of is to have the NEXT button disabled until there are at least 2 accounts?
Unless you think NEXT should also enter any address that is filled in the field still
