### ISSUE TITLE
Error creating Multisig Step 3/3

### ISSUE THREAD

**Issue by qtipwax** [LiskHQ/lisk-ui#36]
Testnet 0.2.1.  Chrome browser.  All 3 accounts had more than 10 Lisks during this step.  Error message seems not to return a valid Lisk account number?
<img width="428" alt="error2" src="https://cloud.githubusercontent.com/assets/12992198/15053495/c94764a6-12b7-11e6-890b-7ef9bc5561c2.PNG">

**Comment by karmacoma** [comment]
Although it's not very clear, the number returned in the error message represents the unconfirmed transaction id. I agree it needs to be changed.
