### ISSUE TITLE
Multisig Transaction Does not require Multisignatures.

### ISSUE THREAD

**Issue by qtipwax** [LiskHQ/lisk-ui#37]
Testnet 0.2.1.  Chrome browser.  Seems to be processed as a regular transaction.
<img width="464" alt="multi" src="https://cloud.githubusercontent.com/assets/12992198/15053982/169368e8-12ba-11e6-9f35-8349f46583ee.PNG">
<img width="405" alt="multi1" src="https://cloud.githubusercontent.com/assets/12992198/15053994/23aad5de-12ba-11e6-923c-34ac654b99af.PNG">
<img width="839" alt="multi2" src="https://cloud.githubusercontent.com/assets/12992198/15054001/2885fc14-12ba-11e6-9d6a-7ef169307f29.PNG">

**Comment by karmacoma** [comment]
@qtipwax Did each multi-signature group member confirm the initial transaction, i.e. the addition to the group? This is required before the group can become active for the given account.

**Comment by fix** [comment]
duplicating #41
