### ISSUE TITLE
Forging Center - Rank Animation is wrong

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-ui#38]
The bar should start at the top, it starts somewhere in the middle. 

![image](https://cloud.githubusercontent.com/assets/9763350/15091753/9b3be162-1452-11e6-80da-237eb0d5fd7d.png)

(Picture taken from the community)

**Comment by mrv777** [comment]
This is caused by ``` var totalDelegates = 108; ``` here:
https://github.com/LiskHQ/lisk-ui/blob/development/js/controllers/forgingController.js#L134

**Comment by karmacoma** [comment]
Well spotted @mrv777, thanks 👍
