### ISSUE TITLE
Multisignature GUI buginess

### ISSUE THREAD

**Issue by TraderBill** [LiskHQ/lisk-ui#46]
- I enabled 2-of-2 multisignature on 11363614320457116995L (account #1)

- I added 21222387859400980L (account #2) as 2nd account

- both accounts had 10 Lisk balance

- I login to 11363614320457116995L (account #1)
"Multisignature" tab on left side sporadically disappears and re-appears

"My Multisignature Groups" box sporadically disappears and re-appears

- 11363614320457116995L (account #1) says confirmations needed 1/2
http://imgur.com/nSHTDgo

- I login to 21222387859400980L (account #2)

I don't see any "Multisignature" tab in account #2

I don't see any option for adding a 2nd confirmation to the transaction in account #2
http://imgur.com/9ug9VLx

I tried on 2 of my nodes and testnet.lisk.io using both google chrome and firefox

**Comment by fix** [comment]
My opinion, is that a multisignature management could be an (d)app  in itself, depending on the use of it:
- creation page of a multisignature account, detecting "cold wallet"
- creating a signed transaction trigger a page creation where people can review the transaction (comment, chat, attach docs etc...) and sign
- signing a transaction trigger a mail to the other signature holders, so they can review it online
- validated transaction trigger a mail to signature holders
- etc...
