### ISSUE TITLE
Copy-to-clipboard button not working

### ISSUE THREAD

**Issue by marijnbent** [LiskHQ/lisk-ui#47]
When clicking the button to copy a transaction or block id, nothing happens. At least on a Macbook.
<img width="542" alt="schermafbeelding 2016-05-19 om 12 43 02" src="https://cloud.githubusercontent.com/assets/11903095/15391156/e98c7360-1dbf-11e6-96c1-25d7e798c6c6.png">

**Comment by mrv777** [comment]
Do you have Adobe flash blocked?
I believe it uses ZeroClipboard.swf to work

**Comment by karmacoma** [comment]
We could switch to using this: https://clipboardjs.com/. Would be good to remove use of flash completely. But I see there is no or limited support for Safari.

**Comment by mrv777** [comment]
^^^I would switch to clipboardjs for now at least.  There is a workaround at the bottom I see for Safari, that will at least easily allow a tooltip message to appear on Safari, while still selecting the text

**Comment by marijnbent** [comment]
JS would be indeed better. The weird thing is, the clipboard button on the lisk explorer _does_ work, which works using flash.
