### ISSUE TITLE
nmp install creates Permission Deinied

### ISSUE THREAD

**Issue by nejt** [LiskHQ/lisk-ui#5]
When I pulled independently - since git submodule public didn't work - to try to build lisk a lot of  errors occurred on nmp install. 

Permission denied and cannot read from remote repository.

**Comment by MaxKK** [comment]
Hello @nejt, please run `sudo npm install`.

**Comment by MaxKK** [comment]
@nejt Did it work and the problem was resolved?

**Comment by nejt** [comment]
No...it did not. I tried to install as root, and even used sudo and it still gave me the errors. 
Sorry, it took me longer to return. I have been travelling.

**Comment by MaxKK** [comment]
Seems like you don't have ssh and git setup. This is necessary if you want to build it from the source code.

Take a look at this video: https://www.youtube.com/watch?v=3_QBw6Qd-Lk

**Comment by nejt** [comment]
OK...it looks like from the video I didn't gen an rsa key an link that to my github. 
You may want to include that step in your written instructions on the Lisk & github page.
