### ISSUE TITLE
Invalid Lisk amount

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-ui#50]
<img width="604" alt="screen shot 2016-05-25 at 10 41 20" src="https://cloud.githubusercontent.com/assets/9548618/15533655/e2de84a4-2265-11e6-9857-3128a38c7ed3.png">

Obviously, issue :)

**Comment by mrv777** [comment]
I think the issue is with decimal values, as I had a similar issue

**Comment by fix** [comment]
yes it is. related #52

**Comment by fix** [comment]
related #52
