### ISSUE TITLE
Account menu bug

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-ui#54]
Sometimes when user click on account menu settings pop-box remains hidden below other bar.
<img width="127" alt="screen shot 2016-05-25 at 11 00 31" src="https://cloud.githubusercontent.com/assets/9548618/15537843/f02b37b6-2278-11e6-8569-e3fc482f82e4.png">
After ~5-20s it loads correctly
<img width="177" alt="screen shot 2016-05-25 at 11 00 26" src="https://cloud.githubusercontent.com/assets/9548618/15537849/00ddd780-2279-11e6-9b61-0bad46e5fe1d.png">
Anyway usually it's fine. It's not related to login.lisk.io overload. Bug occurs also on independent nodes.

I assume it's related to delay while checking if user have enabled 2nd passphrase or not, solution for this maybe at first, loading side bar with pre-defined menu items like "My Profile","Settings","Logout", and as soon we get reply from node, showing option to enable passphrase in case 2nd passphrase is disabled.

**Comment by fix** [comment]
yes sometimes the node has some small desync (like no blocks received for over 10s), so the node is not answering the requests until resync, which takes a few seconds. Thanks for poiting this out, we will work on a fix (ie caching this info).

**Comment by fix** [comment]
Do you still have the issue?
