### ISSUE TITLE
Login Problem on IE11

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-ui#57]
It's not possible to login on the IE11. 

Error msg: Passphrase must be a valid BIP39 mnemonic code.

**Comment by mrv777** [comment]
Odd, I thought it would have been fixed here: https://github.com/LiskHQ/lisk-ui/issues/31

**Comment by mrv777** [comment]
It looks like it was updated to 0.11.0, however the IE Edge fix wasn't introduced until 0.13.2.  Not sure why the code isn't updated all the way to 1.0.1

References:
https://github.com/bitpay/bitcore-mnemonic/commits/v0.13.2
https://github.com/bitpay/bitcore-mnemonic/releases/tag/v1.0.1
