### ISSUE TITLE
GUI voting broken

### ISSUE THREAD

**Issue by arisAlexis** [LiskHQ/lisk-ui#58]
I used the Lisk Autovote script to vote through my node.

Now my node reports votes for more than 24H ago that don't appear on others' nodes. 
As an exmple I upload a screenshot here for a vote to bangomatic and vrlc92 that appear in my gui but not in the login03.lisk.io api call `https://login03.lisk.io/api/accounts/delegates/?address=7979991174011253563L`

![screenshot from 2016-05-27 15 13 50](https://cloud.githubusercontent.com/assets/1141823/15609224/021ba922-241f-11e6-8fff-eef05bfb2c2a.png)

I can also not remove the vote because it doesn't appear on the votes list. Only on the delegates list.

**Comment by arisAlexis** [comment]
Voting from login03.lisk.io did work and it doesn't show the votes in the gui as my node (and they are both on the same blockheight!). 

if you want access to my node to test ping me on chat with the same username and I will tell you the address.

**Comment by fix** [comment]
Difficult now to see what happens without transactionId. It looks like one of the nodes were out of sync, imho

**Comment by fix** [comment]
By the way the voting tool is broken because it causes the several vote transactions being included in a block, which is not possible. There could be a bug where this case is accepted and then broadcasted by your node and then rejected by active delegates.

**Comment by fix** [comment]
not sure how to assess the issue now @arisAlexis Quite a few bug have been fixed in 0.3.2 by @karmacoma 

Can you test again if you still have the issue?
