### ISSUE TITLE
"Remember" login does not work

### ISSUE THREAD

**Issue by thinkloop** [LiskHQ/lisk-ui#62]
Refreshing the dashboard page after checking "remember during session" asks for passphrase again

**Comment by mrv777** [comment]
I don't think "remember during session" works that way.  It just remembers while you are logged in, so you don't have to type it in again when you send LSK or anything like that.  When you refresh the page, you are starting a new session

**Comment by ByronAP** [comment]
mrv77 is correct, this behavior is by design.

**Comment by thinkloop** [comment]
ok!
