### ISSUE TITLE
The dialog is closed and success message is displayed when I clicked multiple times on the buttons "Send lisk" and "Confirm second passphrase"

### ISSUE THREAD

**Issue by vrlc92** [LiskHQ/lisk-ui#68]
The dialog is closed and success message is displayed when I clicked multiple times on the buttons "Send lisk" and "Confirm second passphrase". 

**Notes:**
- My account has 0 lisks.
- The transaction wasn't made with sucess, the problem is only in the UI.

![send_transaction](https://cloud.githubusercontent.com/assets/937766/16200075/3d6822c8-36e2-11e6-86b9-3e92658d2106.gif)

![generatesecondpassphrase](https://cloud.githubusercontent.com/assets/937766/16200074/3d66c0e0-36e2-11e6-9a8e-f16ef6883c32.gif)

**Comment by vrlc92** [comment]
The same problem occurs in:
- Register delegate
- Vote/unvote delegates.

**Comment by slaweet** [comment]
I just tested this issue and it is no longer possible to click "Send Lisk" more than once as after the first click it becomes disabled:
![send_disabled](https://cloud.githubusercontent.com/assets/1254342/24196210/2bb903d2-0efd-11e7-8304-d63b284becb7.png)
