### ISSUE TITLE
Web Client login locked to Edge/IE

### ISSUE THREAD

**Issue by jfernanz** [LiskHQ/lisk-ui#69]
Some accounts get "locked" to certain browsers. Tested on a Windows 10 Computer.

Able to Login through:
- Microsoft Edge (Version 25.10586.0.0)
- Internet Explorer 11 (Version 11.420.10586.0)

Not able to login through (Passphrase must be a valid BIP39 mnemonic code.):
- Google Chrome (Version 51.0.2704.106 m)
- Mozilla Firefox (Version 47.0)
- Opera (Version 38.0)
- Brave (Version 0.10.4)

**Comment by fix** [comment]
should be fixed with 0.3.2, can you confirm @jfernanz ?

**Comment by Isabello** [comment]
This is fixed.
