### ISSUE TITLE
Missing progress indicator while syncing

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-ui#71]
While node is syncing there should be progress indicator with current local height and current network height, maybe also some fancy progress bar

**Comment by fix** [comment]
There is already percentage, you mean add a progress bar on top of this?

**Comment by karek314** [comment]
Yes, progress bar on top of this. Right, there is percentage but only when syncing node with network  - in case blockchain is being rebuild there is only information "Blockchain loading" and this is misleading.
