### ISSUE TITLE
Negative Blockchain time stamp value in lisk client ui

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-ui#74]
Moved from: https://github.com/LiskHQ/lisk/issues/167.

Courtesy of: @Nerigal.

**Comment by alihaghighatkhah** [comment]
This issue happens when the client's system time is not correct, i.g. the time stamp is ahead of system time, then the relative time is shown in negative. but it's possible to choose "Show full time" and see the date-time instead of related time. I think we  can close this for now.
