### ISSUE TITLE
Fix broken images and pimp the applications site

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-ui#78]
This doesn't look good currently: https://login.lisk.io/dappstore
![liskui](https://cloud.githubusercontent.com/assets/19614645/19416418/e43e1ee0-938f-11e6-8a0d-9bb39438da57.jpg)

**Comment by karmacoma** [comment]
Closing as application directory feature has been disabled since: 0bd5bef5cf2f64eaee3bb0dc0b31f4bd4a9d5c5f
