### ISSUE TITLE
Search for delegates username

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk-ui#8]
Just a reminder: As I already told @karmacoma, it would be really helpful to be able to search for delegates usernames in the upcoming clients.

**Comment by fix** [comment]
closing it because fixed here:
https://github.com/LiskHQ/lisk/blob/9f8666c8d7f4f085992c2819bc01f15e31bbf963/modules/delegates.js#L295

**Comment by karmacoma** [comment]
Reopening, yes endpoint has been added to backend, this issue relates to the frontend implementation of it.

**Comment by fix** [comment]
ok
