### ISSUE TITLE
Blocks are not being loaded - instead broken table

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-ui#84]
It happens sometimes for me - version 0.4.1
<img width="1444" alt="screen shot 2016-11-20 at 00 30 48" src="https://cloud.githubusercontent.com/assets/9548618/20459283/a7c21858-aebb-11e6-8f97-2d699c28f29c.png">

**Comment by Tosch110** [comment]
I was not able to reproduce this error. When it is being encountered, please reopen this issue with a description on how to reproduce. Thanks.
