### ISSUE TITLE
Needed: Guaranteed transaction after click on "SEND", or at least a confirmation.

### ISSUE THREAD

**Issue by MaxKK** [LiskHQ/lisk-ui#9]
Submitted by Lisk community member Lisk:

>  I just tried to transfer some lisks but after i clicked the send button nothing happened. In other words, i did not get confirmation that the lisks were sent. So i clicked several more times, with the result that same transfer happened three times in a row. Would it be suggestion to add something like a confirmation after you click send?

**Comment by qtipwax** [comment]
Same problem here 0.2.1.  Chrome browser.  Logged into my node.

**Comment by qtipwax** [comment]
Had the same issue but in the cloudy background, I saw a transaction.  Stopped clicking and closed the box.

**Comment by fix** [comment]
This is not an easy one from UX perspective:
- The only thing you can be sure is that the transaction has been sent. This does not mean it has been validated by the blockchain.
- There is a waiting time for 1st confirmation (10s), so it needs to have a special view to make the user wait. Ideally we should resonnably confirm the transaction after 5 to 10 confirmations.
- If node is in fork, it could happen that there is a confirmation (or several) and actually not really validated. I would mitigate by polling several peers to see if the transactions got through

Aside from that, the UX should prevent from sending/creating a transaction if the node is in fork on not in sync.

**Comment by qtipwax** [comment]
A spinning circle type of "waiting" symbol or something might be useful.  Just today on testnet, someone sent 242 Lisks two times because of this issue I believe.
