### ISSUE TITLE
Broken layout in Forging Screen

### ISSUE THREAD

**Issue by vrlc92** [LiskHQ/lisk-ui#96]
![screen shot 2017-02-22 at 11 12 45](https://cloud.githubusercontent.com/assets/937766/23215144/1ed8d0e8-f8f0-11e6-848a-6efbe40eb2d2.png)

**Comment by Isabello** [comment]
This will not be fixed. The only thing you can do is expand it beyond the
minimum resolution.

**Comment by vrlc92** [comment]
Can not develop a fluid layout?

**Comment by Isabello** [comment]
We are not putting time into Lisk UI because its being disabled next release.

**Comment by vrlc92** [comment]
Okay, that makes sense.

**Comment by karmacoma** [comment]
As @Isabello stated we won't be developing `lisk-ui` much further. Closing issue as already labelled `wontfix`.
